modLoader = "javafml"
loaderVersion = "${loader_version_range}"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''
#logoFile = ""

[[dependencies.wheatmarket]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.wheatmarket]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.wheatmarket]]
modId = "ldlib2"
type = "required"
versionRange = "[${ldlib2_version},)"
ordering = "AFTER"
side = "BOTH"
